[package]
name = "blog"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2021"

[[bin]]
name = "blog"
path = "src/blog.rs"

[dependencies]
handlebars = { version = "4", features = ["dir_source"] }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
comrak = "0.18"
regex = "1.9"
sass-rs = "0.2"
chrono = "0.4"

[workspace]
members = ["serve"]
